name: TL_ERC
channels:
  - anaconda
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pip=19.2.3
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9b
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.0.10
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ninja=1.9.0
  - numpy-base=1.16.4
  - olefile=0.46=py36_0
  - openssl=1.1.1c
  - pillow=6.1.0
  - pycparser=2.19=py36_0
  - python=3.6.9
#  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - setuptools=41.0.1=py36_0
  - sqlite=3.29.0
  - tk=8.6.8
  - wheel=0.33.4=py36_0
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    #- libstdcxx-ng==9.1.0
    - torchvision==0.4.1
    #- libgfortran-ng==7.3.0
    #- ncurses==6.1
    #- readline==7.0
    #- libedit==3.1.20181209
    #- libgcc-ng==9.1.0
    - boto==2.49.0
    - boto3==1.9.224
    - botocore==1.12.224
    - chardet==3.0.4
    - cymem==1.31.2
    #- cytoolz==0.8.2
    - dill==0.2.9
    - docutils==0.15.2
    - ftfy==4.4.3
    - gensim==3.8.0
    - html5lib==1.0.1
    - idna==2.8
    - jmespath==0.9.4
    - joblib==0.13.2
    - murmurhash #==0.26.4
    - nltk==3.2.5
    - numpy==1.17.1
    - pandas==0.20.3
    - pathlib==1.0.1
    - pip==19.2.3
    - plac==0.9.6
    - preshed==1.0.1
    - protobuf==3.9.1
    - python-dateutil==2.8.0
    - pytorch-pretrained-bert==0.6.2
    - pytz==2019.2
    - regex==2017.11.9
    - requests==2.22.0
    - s3transfer==0.2.1
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - six==1.12.0
    - smart-open==1.8.4
    - spacy #==1.9.0
    - tensorboardx==1.1
    - termcolor==1.1.0
    - thinc #==6.5.2
    - toolz==0.10.0
    - tqdm==4.15.0
    - ujson #==1.35
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - wrapt==1.11.2

